# Travis CI configuration file

# Configuration
dist: focal  # Ubuntu 20.04
language: bash
services:
    - docker  # Need docker for containers

# Build the container
before_install:
    - docker pull python:slim
    - docker build -t syllabus .

# Run tests in the container
script:
    - docker run --rm --name syllabus -i -t -v $(pwd):/syllabus syllabus ./travis.sh
